### PR TITLE
Add podspec and instructions

### PR DESCRIPTION
**Pull request by igrayson**

### CODE REVIEW

**Comment by joeferraro** [comment]
@igrayson can you fix the reference to "react-native-sqlite-storage"?

**Comment by igrayson** [comment]
Oops :>

**Comment by igrayson** [comment]
It's fixed.

**Comment by johncblandii** [comment]
Can we get this one merged? It'd really help.

**Comment by joeferraro** [comment]
Have you tested the PR?

**Comment by igrayson** [comment]
We've been using this PR in our fork; it's been tested by us.

**Comment by igrayson** [comment]
ping

**Comment by jcurtis** [comment]
Should the command be this?

`pod 'react-native-cookies', :path => '../node_modules/react-native-cookies'`

Since you'd be running `pod install` from the `/ios` directory.

**Comment by johncblandii** [comment]
@jcurtis, only if your `Podfile` is in the `ios` directory. I don't put mine there. I like to run all commands (`pod`, `npm`, etc) from the app root.

**Pull request closed without merging**
