### PR TITLE
Upgrade Android build tools to 25.0.2

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
@joeferraro do you mind merging this?

**Comment by Brian-Kaplan** [comment]
@joeferraro please merge

**Comment by Brian-Kaplan** [comment]
@joeferraro if you have issues with this please bring them up. My project uses 25.0.2 and we really this library to get upgraded.

**Comment by joeferraro** [comment]
@Brian-Kaplan appreciate the enthusiasm, but I see all notifications from GitHub and don't need multiple messages.

**Pull request merged**
