### PR TITLE
Android support

### LINKED ISSUE #7: Android Support
I want to manage cookie in react native.
So I found this modules, but this is not working in android.

Would you mind to make another version that supports android platform?

Thanks.

### PR DESCRIPTION
**Pull request by Psykar**
This is in a useable state now (although I couldn't implement getAll for android)
Some cleanups and rebasing required, but thought I'd throw it out there for comment.

Closes #7

### CODE REVIEW

**Comment by mrpatiwi** [comment]
This is exactly what I need

**Comment by joeferraro** [comment]
@Psykar awesome, will work on it this week. cheers :+1:

**Comment by joeferraro** [comment]
@Psykar any chance you could [squash your commits](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes)?

**Comment by Psykar** [comment]
Yeah, will clean up this week sometime, but thought I'd throw it up first for comment :-)

**Comment by joeferraro** [comment]
cool thanks @Psykar :-)

**Comment by Psykar** [comment]
Cleaned / squashed / ready

Thanks :)

**Comment by israelidanny** [comment]
@Psykar I just tried to `npm install` your fork into my project, but for some reason no matter what I do it keeps saying:
`Import libraries to android 'rnpm link'`

I did the `rnpm link` step and it shows:
```
rnpm info Linking react-native-cookies android dependency
```

**Comment by Psykar** [comment]
From your message it looks like rnpm did it's job correctly... Unfortunately there's not a lot of doco (and no official doco) around linking Android libraries (I mostly found other projects doing similar things) 

I would look at the changes made by rnpm link (it should edit a bunch of files in your project's repo), including 
android/app/build.gradle
```compile project(':react-native-cookies')
```
android/app/src/main/java/com/app/MainActivity.java
```import com.psykar.cookiemanager.CookieManagerPackage;
...
.addPackage(new CookieManagerPackage())```
android/settings.gradle
include ':react-native-cookies'
project(':react-native-cookies').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-cookies/android')
```

If all those changes are there it *should* be working.

**Comment by bartonhammond** [comment]
Any reason why this can't be merged?  I would help with testing but not sure how to "npm install pull-request".

**Comment by bartonhammond** [comment]
1) Created new project 'react-native init oAuth'
2) react-native: **0.18.1**
3) npm install -g rnpm
4) 
```
~/projects/stargazers/temp/oAuth$ rnpm link react-native-cookies
rnpm info Linking react-native-cookies android dependency 
rnpm info Android module react-native-cookies is already linked 
```

5) Checked android files:
* android/app/build.gradle
- [x] ```compile project(':react-native-cookies')```
* android/app/src/main/java/com/app/MainActivity.java
- [ ] ```import com.psykar.cookiemanager.CookieManagerPackage```
- [ ] ```.addPackage(new CookieManagerPackage())```
- [x] ```include ':react-native-cookies'```
* android/settings.gradle
- [x] include ':react-native-cookies'
- [x] project(':react-native-cookies').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-cookies/android')

I'm not sure what to do w/ ```MainActivity.java``` as there is no ```ReactInstanceManager.builder()``` where ```.addPackage..``` would usually be.

Is this something to do w/ changes for RN 0.18.1?

**Comment by Psykar** [comment]
@bartonhammond just use this line in package.json for now `    "react-native-cookies": "https://github.com/Psykar/react-native-cookies/tarball/master"`

I haven't tested 0.18.1 so could be it. My shrinkwrap is at https://gist.github.com/Psykar/5a69e662a170fe9d51f5 if you want to compare versions.
Unfortunately I can't push the main project I'm  using this on as it's not public code, but I'll see if I can get a quick example done in the next couple days.

**Comment by bartonhammond** [comment]
@Psykar I have a small iOS project that's working w/ a Hapi backend doing oAuth w/ GitHub.  If I can get your android version working I'll make the project (client & server) available.

The change to the android  ```android/app/src/main/java/com/app/MainActivity.java```  file is substantial.  I'll have to wait for your direction before continuing.

**Comment by Psykar** [comment]
Got it, look here:
https://github.com/rnpm/rnpm/issues/77#issuecomment-174350911

I suspect this will be fixed in rnpm eventually, no changes required to this PR to get it working though.

**Comment by bartonhammond** [comment]
@Psykar  Sweet!  Thanks for looking in to it!

**Comment by Psykar** [comment]
Example repo here: https://github.com/Psykar/react-native-cookies-example

**Comment by bartonhammond** [comment]
1) How can I see all the cookies in Android like in iOS?  

2) Can't invoke RNCookieManagerAndroid.clearAll
screen shot 2016-01-25 at 2 54 53 pm

**Comment by Psykar** [comment]
1) Not technically possible. Android restricts access to only a domain name that you give it.
2) It's a string you put directly on your HTTP request's header (which actually kind of makes it easier to use) 
`request.headers = {'Cookie': CookieManager.getCookieHeader('example.com')}`
3) Will have to take a look at clearAll, worked for me, but didn't test extensively.

**Comment by bartonhammond** [comment]
@Psykar 
1) - Not a problem now for me as I finally figured out how to use GenyMotion, localhost w/ /etc/hosts & comparing w/ iOS cookie manager - I now have the domain name I needed
2) Now w/ the right 'domain' name (e.g. ```https://github.com```) I have the cookie session token now
3) Definitely need the ```clearAll```

Thanks for looking into this!

**Comment by Psykar** [comment]
@bartonhammond I've pushed an update, I'd just missed exporting that function on the android side of things.

Note that the API has changed slightly (simplified) - `get` and `setFromResponse` now (previous methods are the same)
My example has also been updated
https://github.com/Psykar/react-native-cookies-example

@joeferraro any chance of getting this merged now?

**Comment by bartonhammond** [comment]
@Psykar 
1) update local repo eg ```cd react-native-cookie-example```
2) git pull
3) rm node_modules/react-native-cookies
4) npm install 
  *note: package.json has
``` 
"react-native-cookies": "https://github.com/Psykar/react-native-cookies/tarball/master"
```
5) genymotion start galaxy 5
6) react-native run-android 
7) see below:

screen shot 2016-01-26 at 6 44 16 pm

**Comment by Psykar** [comment]
Guessing your Android API level is below 21?

Guess I have to write annoying callback code now :(

**Comment by bartonhammond** [comment]
I'm not sure what level it is.  I setup my android environment following RN
instructions months ago.  I thought it was 23 but I'll check tomorrow.

**Comment by Psykar** [comment]
It's more dependant on what emulator you were running and what your minimum API level spec was.

Regardless, updated to run on lower API levels (basically wraps FB's `com.facebook.react.modules.network.ForwardingCookieHandler` now which does most of the heavy lifting)

**Comment by maraujop** [comment]
I can confirm @Psykar that this PR is working for us in Android. 

We use `setFromResponse` in Android and set in iOS and its working in both platforms.

**Comment by bartonhammond** [comment]
Looks good to me too! (Android Galaxy S5 API 19)  Thanks @Psykar

**Comment by joeferraro** [comment]
Hey guys, thanks again for working through this. I don't have the time to properly test the Android version so I'll take it from @bartonhammond, @maraujop, and @Psykar that this is good to go. Can you guys give me a final confirmation? Cheers!

**Comment by bartonhammond** [comment]
@joeferraro I tested both iOS and Android - looks good

**Comment by maraujop** [comment]
I would remove the `untested` in the README, it arouses suspicion:

```diff
// Set cookies from a response header (untested)
// Set cookies from a response header
```

Not sure if this is intended by @Psykar but `setFromHeader` only has worked in Android for us, in iOS it was raising an exception. If so, I would add this to the README.

Besides this, looks good

**Comment by israelidanny** [comment]
Also confirming, got it to work smoothly on an app that's going into
production in a few days.

**Comment by Psykar** [comment]
@maraujop you might have an older version of this PR then? Current readme doesn't have that line, and I changed the method to `setFromResponse` (apologies).

**Comment by Psykar** [comment]
@joeferraro I'm happy with it now - changes to the README are already in the PR.

**Comment by mart2967** [comment]
I had been running into this:

```
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-cookies : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.582 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

until I compared my files with the example project and realized that the line
`project(':react-native-cookies').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-cookies/android')`
had an extra `../` at the beginning. I'm fairly sure I didn't put that in, so it could be an artifact of the linking process. Just wanted to put this here in case anyone else has run into it.

**Comment by Psykar** [comment]
@mart2967 if you can reproduce it, open an issue here: https://github.com/rnpm/rnpm

**Comment by Psykar** [comment]
Thought I'd ping this again @joeferraro :)

**Comment by joeferraro** [comment]
thanks all. this has been merged!

**Pull request merged**
